export const ETH_GOOGLE_TRENDS_FETCHED = 'googleTrends.ETH_GOOGLE_TRENDS_FETCHED';

export const BTC_GOOGLE_TRENDS_FETCHED = 'googleTrends.BTC_GOOGLE_TRENDS_FETCHED'

export const XRP_GOOGLE_TRENDS_FETCHED = 'googleTrends.XRP_GOOGLE_TRENDS_FETCHED'

export const XEM_GOOGLE_TRENDS_FETCHED = 'googleTrends.XEM_GOOGLE_TRENDS_FETCHED'

export const LTC_GOOGLE_TRENDS_FETCHED = 'googleTrends.LTC_GOOGLE_TRENDS_FETCHED'
