module.exports = {
  "CNBC": "msm",
  "Bloomberg": "msm",
  "Nasdaq": "msm",
  "Inc.com": "msm",
  "EconoTimes": "msm",
  "Fortune": "msm",
  "Yahoo Finance": "msm",
  "Business Insider": "msm",
  "Forbes": "msm",
  "Financial Times": "msm",
  "The Economist": "msm",
  "The Verge": "msm",
  "PR Newswire (press release)‎": "msm",
  "Investopedia": "msm",
  "Mic": "msm",
  "TechCrunch": "msm",
  "Futurism": "msm",
  "Motherboard": "msm",
  "VentureBeat": "msm",
  "CoinTelegraph": "crypto",
  "The Merkle": "crypto",
  "newsBTC": "crypto",
  "Inside Bitcoins": "crypto",
  "Coinspeaker": "crypto",
  "CoinDesk": "crypto",
  "ETHNews": "crypto",
  "CryptoCoinsNews": "crypto",
  "CryptoNinjas": "crypto",
  "Bitcoin Magazine": "crypto",
  "Quartz": "msm",
  "Seeking Alpha": "msm",
  "Bitcoin News (press release)": "crypto",
  "Ethereum world news (blog)": "crypto",
  "MarketWatch": "msm",
  "Mashable": "msm",
  "HuffPost": "msm",
  "Huffington Post": "msm",
  "Motley Fool": "msm",
  "New York Times": "msm",
  "WIRED": "msm",
  "Haaretz": "msm",
  "CoinJournal (blog)": "crypto",
  "Bitcoinist": "crypto",
  "Crypto Insider (press release)": "crypto",
  "Crypto Insider": "crypto",
  "Ethereum World News (blog)": "crypto",
  "Coin Idol (press release)": "crypto",
  "The Atlantic": "msm",
  "The Guardian": "msm"
}
